export { default as Home } from "./Home";
export { default as History } from "./History";
export { default as GamesPvE } from "./GamesPvE";
export { default as GamesPvP } from "./GamesPvP";
export { default as GamesFree } from "./GamesFree";
export { default as Leaderboard } from "./Leaderboard";
export { default as Rewards } from "./Rewards";
export { default as Tournaments } from "./Tournaments";
export { default as Whitepaper } from "./Whitepaper";
